repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.15
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: uv-ruff
        name: ruff
        entry: uv run ruff check
        language: system
        types: [python]
        pass_filenames: true
        stages: [pre-commit]

      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]